#define	SAVE_PROFILE_MSG        (sysinfo.japanesef ? "プロファイルを保存しました。":"Sevaed profile.")
#define	WAITING_MSG				(sysinfo.japanesef ? "しばらくお待ちください。":"Please Wait...")
#define	NOT_OPEN_OR_CREATE_MSG	(sysinfo.japanesef ? "ファイルが見つからないか、ファイル名が作れません。":"Not Found File or Don't Create Name of File")
#define	TMPFILE_NOT_OPEN_MSG	(sysinfo.japanesef ? "テンポラリファイルが開けません":"Not Open Temporary File")
#define	SEARCHING_MSG			(sysinfo.japanesef ? "検索中...":"Searching...")
#define	NOT_FOUND_MSG			(sysinfo.japanesef ? "見つかりませんでした ":"Not Found ")
#define	FOUND_MSG				(sysinfo.japanesef ? "見つかりました ":"Found ")
#define	SAVEING_MSG				(sysinfo.japanesef ? "保存中":"Saveing")
#define	SAVESUCCESS_MSG			(sysinfo.japanesef ? "保存しました":"Save success")
#define	NEWFILE_MSG				(sysinfo.japanesef ? "新しいファイルです":"New File")
#define	READING_MSG				(sysinfo.japanesef ? "読み込み中":"Reading")
#define	FILE_NOT_FOUND_MSG		(sysinfo.japanesef ? "ファイルが見つかりません ":"File Not Found ")
#define	ABANDON_MSG				(sysinfo.japanesef ? "破棄します":"Abandon")
#define	CNTRL_INPUT_MSG			(sysinfo.japanesef ? "制御文字入力 (^x) ":"Input CONTROL Character (^x)")
#define	REPLACED_MSG			(sysinfo.japanesef ? "置換しました":"Replaced")
#define	PERMISSION_MSG			(sysinfo.japanesef ? "書き込み権がありません":"Permission denied")
#define	MEMORY_ERR_MSG			(sysinfo.japanesef ? "メモリが足りません ":"Not Enough Memory ")
#define	DONT_WRITE_FILE_MSG		(sysinfo.japanesef ? "ファイルが書けません ":"Impossible to Write File")
#define	DONT_OPEN_MORE_FILE_MSG	(sysinfo.japanesef ? "これ以上開けません.":"No more Files Opened")
#define	PIPE_OPEN_ERR_MSG		(sysinfo.japanesef ? "パイプオープンエラー ":"Pipe Open Error")
#define	FILE_EXIST_MSG			(sysinfo.japanesef ? "ファイルが存在します ":"File Exist ")
#define	THIS_FILE_OPENED_MSG	(sysinfo.japanesef ? "既にオープンされています":"This File Opened ")
#define	REPLACE_MSG				(sysinfo.japanesef ? "置換しますか ":"Replace ")
#define	REPLACE_WITH_ASK_MSG	(sysinfo.japanesef ? "確認しますか":"Replace With Asking")
#define	TMPNAME_NOT_CREATE_MSG	(sysinfo.japanesef ? "テンポラリファイル名が作れません ":"Not Create Temporary Name")
#define	THIS_FILE_CHANGED_MSG	(sysinfo.japanesef ? "このファイルは変更されています.. 保存しますか":"This file Changed.. Do you save")
#define	SAVE_FILE_CHANGED_MSG	(sysinfo.japanesef ? "保存先のファイルがアクセスされてます..保存しますか":"Target File is rewritten by other process .. Do you save")
#define	TARGET_FILE_CHANGED_MSG	(sysinfo.japanesef ? "保存先のファイルがアクセスされてます":"Target File is rewritten by other process .. Do you save")
#define	EXIST_CHANGED_FILE_MSG	(sysinfo.japanesef ? "変更されたファイルがあります.. 保存しますか":"Exist Changed files.. Do you save")
#define	TARGET_FILE_PERM_MSG	(sysinfo.japanesef ? "ファイルが読めなくなりました。":"Target file is changed permittion")
#define	ARE_YOU_SURE_MSG		(sysinfo.japanesef ? "このファイルは変更されています.. よろしいですか...":"This file Changed.. Are You Sure")
#define	LINE_BUFFER_OVER_MSG	(sysinfo.japanesef ? "行バッファがいっぱいです.":"Line Buffer Over Flow .")
#define	CAN_NOT_OPEN_DIR_MSG	(sysinfo.japanesef ? "ディレクトリがオープンできません ":"Can't Open Directory ")
#define	GETS_FIND_MSG			(sysinfo.japanesef ? "検索文字列 :":"Find :")
#define	GETS_REPLACE_MSG		(sysinfo.japanesef ? "置換文字列 :":"Replace With :")
#define	GETS_TAB_STOP_MSG		(sysinfo.japanesef ? "タブストップ数 :":"Tab Stop :")
#define	GETS_SHELL_MSG			(sysinfo.japanesef ? "子プロセス :":"Shell :")
#define	GETS_SYSTEM_MSG			(sysinfo.japanesef ? "システム :":"System :")
#define	RENAME_MSG				(sysinfo.japanesef ? "ファイル名の変更 :":"Rename file :")
#define	OPEN_MSG				(sysinfo.japanesef ? "新規ファイル :":"Open :")
#define	INS_MSG					(sysinfo.japanesef ? "ファイル挿入 :":"Open :")
#define	SAVE_AS_MSG				(sysinfo.japanesef ? "名前を変えて保存 .. :":"Save as .. :")
#define	TYPE_EXIT_MSG			(sysinfo.japanesef ? "`exit' でもどります.. ":"Type `exit' to return .. ")
#define	HIT_ANY_KEY_MSG			(sysinfo.japanesef ? "リターンを押してください !! ":"Hit Return Key !! ")
#define	REPLACE_ALL_MSG			(sysinfo.japanesef ? "A)テキスト全体":"All Text")
#define	REPLACE_FORWARD_MSG		(sysinfo.japanesef ? "F)カーソル以降":"Forward Cursor")
#define	REPLACE_BACK_MSG		(sysinfo.japanesef ? "B)カーソル以前":"Back Cursor")
#define	REPLACE_INSIDEBLOCK_MSG	(sysinfo.japanesef ? "I)ブロック範囲":"Inside Block")
#define	READ_KEYDEF_MSG			(sysinfo.japanesef ? "キー定義ファイルを読み込みました..":"Read KeyDefine..")
#define	ENV_MSG					(sysinfo.japanesef ? "環境を読み込みました..":"Read Environment..")

#define	MENU_OPEN_MSG			(sysinfo.japanesef ? "O)ファイルのオープン":"Open")
#define	MENU_CLOSE_MSG			(sysinfo.japanesef ? "C)ファイルのクローズ":"Close current file")
#define	MENU_SAVE_MSG			(sysinfo.japanesef ? "S)ファイルの保存":"Save")
#define	MENU_SAVEAS_MSG			(sysinfo.japanesef ? "A)ファイル名を変えて保存":"Save as ..")
#define	MENU_CLOSE_AF_MSG		(sysinfo.japanesef ? "X)全ファイルのクローズ":"Close all files")
#define	MENU_SAVE_PROFILE_MSG	(sysinfo.japanesef ? "S)プロファイルの保存":"Save Profile")
#define	MENU_RENAME_MSG			(sysinfo.japanesef ? "R)ファイル名の変更":"Rename file")
#define	MENU_REFRESH_CF_MSG		(sysinfo.japanesef ? "U)編集のやり直し":"Refresh current file")
#define	MENU_ESCAPE_SHELL_MSG	(sysinfo.japanesef ? "E)子プロセス":"Escape Shell")
#define	MENU_INSERT_OUTPUT_MSG	(sysinfo.japanesef ? "G)子プロセスの出力を取り込み":"Exec and insert output")

#define	OPT_NUMBER_MSG			(sysinfo.japanesef ? "N)行番号            : ":"Number              : ")
#define	OPT_INPUT_MODE_MSG		(sysinfo.japanesef ? "O)オーバーライト    : ":"Over Write          : ")
#define	OPT_CURSOR_MODE_MSG		(sysinfo.japanesef ? "F)フリーカーソル    : ":"Free Cursor         : ")
#define	OPT_AUTOINDENT_MODE_MSG	(sysinfo.japanesef ? "A)オートインデント  : ":"AutoIndent          : ")
#define	OPT_BACKUP_MSG			(sysinfo.japanesef ? "B)バックアップ      : ":"BackUp              : ")
#define	OPT_TAB_MARK_MSG		(sysinfo.japanesef ? "T)タブマーク        : ":"Tab Mark            : ")
#define	OPT_TAB_SPACE_MSG		(sysinfo.japanesef ? "T)タブ->スペース    : ":"Tab->Space          : ")
#define	OPT_CR_MARK_MSG			(sysinfo.japanesef ? "C)行末マーク        : ":"Cr Mark             : ")
#define	OPT_SEARCH_CH_MSG		(sysinfo.japanesef ? "S)検索時の大／小文字: ":"Search String       : ")
#define	OPT_MESSAGE_MSG			(sysinfo.japanesef ? "J)日本語メッセージ  : ":"Japanese Message    : ")
#define	OPT_KANJICODE_MSG		(sysinfo.japanesef ? "K)漢字コード        : ":"Kanji Code          : ")
#define	OPT_TAB_STOP_MSG		(sysinfo.japanesef ? "T)タブストップ数    : ":"Tab Stop            : ")

#define	HELP_MSG				(sysinfo.japanesef ? "ヘルプ :":"HELP :")

#define	RESTORE_BUFFER_MSG1		(sysinfo.japanesef ? "バッファに残ったファイルを保存しました。\n":"The file in buffer is restored.\n")
#define	RESTORE_BUFFER_MSG2		(sysinfo.japanesef ? "ne -r で復旧します。\n":"You can retrieve with \"ne -r\".\n")
